configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cruz%2Fsystem-prompt-storage-16656c3988bbf383e97753354a0ff7e04ccb3fdcd066ca2db664cab0cfc93451.yml
openapi_spec_hash: 6cdec59fe7268f2dfb8b61e1ecfb2513
config_hash: 0f85d6efdebd08e7eca1e5ba1978b8f0
