configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/cruz%2Fsystem-prompt-storage-ffa4dc8c8c3d13a43dac48387ce7c2b68001877af65bb742d5be16811ff0ad94.yml
openapi_spec_hash: 99fdc584a355b01f6b6b74dc8bb9a9db
config_hash: b0ad8a86c49d8509f33daf789bee91ec
